---
  Description: PRIMEIRO TEMPLATE, FEITO PARA ESTUDOS
  Parameters:
    TipoEC2:
      Type: String
      Default: t2.micro
      AllowedValues:
        - t2.micro
        - t3.micro
      Description: Enter t2.micro or t3.micro. Default is t2.micro.
    KEYPAIR:
      Description: Seleciona a key pair
      Type: AWS::EC2::KeyPair::KeyName
      ConstraintDescription: must be the name of an existing EC2 KeyPair.
  #Mappings:
    #RegionMap: 
      #us-east-1:
        #HVM64: ami-0ff8a91507f77f867
        #HVMG2: ami-0a584ac55a7631c0c
      #us-west-1:
        #HVM64: ami-0bdb828fd58c52235
        #HVMG2: ami-066ee5fd4a9ef77f1
      #eu-west-1:
        #HVM64: ami-047bb4163c506cd98
        #HVMG2: ami-0a7c483d527806435
      #ap-northeast-1:
        #HVM64: ami-06cd52961ce9f0d85
        #HVMG2: ami-053cdd503598e4a9d
      #ap-southeast-1:
        #HVM64: ami-08569b978cc4dfa10
        #HVMG2: ami-0be9df32ae9f92309
  #VPC
  Resources: 
    PrimeiraVPC: 
      Type: AWS::EC2::VPC
      Properties: 
        CidrBlock: 192.168.0.0/24
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'
  #SUBNETS      
    SubnetPUBLICA:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref PrimeiraVPC
        CidrBlock: 192.168.0.0/25
        AvailabilityZone: "us-east-1a"
        MapPublicIpOnLaunch: 'true'
        Tags:
        - Key: name
          Value: subpublica
    SubnetPRIVADA:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref PrimeiraVPC
        CidrBlock: 192.168.0.128/25
        AvailabilityZone: "us-east-1b"
        Tags:
        - Key: name
          Value: subprivada
  #ROTA PUBLICA
    ROTAPUBLICA:
      Type: AWS::EC2::Route
      DependsOn: AttachGateway
      Properties:
        RouteTableId: !Ref ROUTETABLEPUBLIC
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref INTERNETGATEWAY
  #ROTA PRIVADA
    #ROTAPRIVADA:
      #Type: AWS::EC2::Route
      #Properties:
        #RouteTableId: !Ref ROUTETABLEPRIVATE
        #DestinationCidrBlock: 0.0.0.0/24
  #TABELAS DE ROTA
    ROUTETABLEPUBLIC:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref PrimeiraVPC
        Tags:
        - Key: name
          Value: routetablepublic
    ROUTETABLEPRIVATE:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref PrimeiraVPC
        Tags:
        - Key: name
          Value: routetableprivate
  #ASSOCIATION DAS TABELAS DE ROTA
    RouteAssociationPUBLIC:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref SubnetPUBLICA
        RouteTableId: !Ref ROUTETABLEPUBLIC
    RouteAssociationPRIVADA:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref SubnetPRIVADA
        RouteTableId: !Ref ROUTETABLEPRIVATE
  #INTERNET GATEWAY
    INTERNETGATEWAY:
      Type: AWS::EC2::InternetGateway
      DependsOn: PrimeiraVPC
      Properties:
        Tags:
        - Key: name
          Value: igstack
  #ATTACH DO IG NA VPC
    AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref PrimeiraVPC
        InternetGatewayId: !Ref INTERNETGATEWAY
  #ASSOCIAR O INTERNET GATEWAY NA TABELA DE ROTAS PUBLICA
    #IGROUTETABLE:  
      #Type: AWS::EC2::GatewayRouteTableAssociation
      #Properties: 
        #GatewayId: !Ref INTERNETGATEWAY
        #RouteTableId: !Ref ROUTETABLEPUBLIC
  #SECURITY GROUP DA VPC
    SG1teste:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: TUDO LIBERADO
        GroupName: SG1FULL
        VpcId: !Ref PrimeiraVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 0
            ToPort: 65535
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol: tcp
            FromPort: 0
            ToPort: 65535
            CidrIp: 0.0.0.0/0
  #NETWORK ACL (REGRAS SUBNET PUBLICA)
    NETACL1:
      Type: AWS::EC2::NetworkAcl
      Properties:
        VpcId: !Ref PrimeiraVPC
        Tags:
        - Key: name
          Value: netacl1
    InboundRule:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref NETACL1
        RuleNumber: 100
        Protocol: -1 
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 0
          To: 65535
    OutboundRule:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref NETACL1
        RuleNumber: 100
        Protocol: -1 
        Egress: true
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
  #ASSOCIAR A NETWORKACL COM A SUBNET PUBLICA
    SUBACLASSOCIATION1:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties: 
        NetworkAclId: !Ref NETACL1
        SubnetId: !Ref SubnetPUBLICA
  #NETWORK ACL (REGRAS SUBNET PRIVADA)
    NETACL2:
      Type: AWS::EC2::NetworkAcl
      Properties:
        VpcId: !Ref PrimeiraVPC
        Tags:
        - Key: name
          Value: netacl2
    InboundRule:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref NETACL2
        RuleNumber: 100
        Protocol: -1 
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 0
          To: 65535
    OutboundRule:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref NETACL2
        RuleNumber: 100
        Protocol: -1
        Egress: true
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
  #ASSOCIAR A NETWORKACL COM A SUBNET PRIVADA
    SUBACLASSOCIATION2:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties: 
        NetworkAclId: !Ref NETACL2
        SubnetId: !Ref SubnetPRIVADA
####################################################################
  #CRIAR A EC2 (INSTANCIA)
    LINUX1:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: us-east-1a
        ImageId: ami-090fa75af13c156b4
        NetworkInterfaces:
          - AssociatePublicIpAddress: 'true'
            DeviceIndex: '0'
            SubnetId: !Ref SubnetPUBLICA
            GroupSet: [!Ref SG1teste]
        InstanceType: !Ref TipoEC2
        KeyName: !Ref KEYPAIR
        #SubnetId: !Ref SubnetPUBLICA
        #SecurityGroups: !Ref SG1teste
        Tags:
          - Key: name
            Value: ec2linux
            

